version: 0.2

phases:
  install:
    commands:
      - apk add --no-cache --repository http://dl-cdn.alpinelinux.org/alpine/edge/testing --repository http://dl-cdn.alpinelinux.org/alpine/edge/main lcov zip
  pre_build:
    commands:
      - git config --global user.email \"you@example.com\"
      - git config --global user.name \"John Doe\"
      - forge install OpenZeppelin/openzeppelin-contracts@v4.8.3
      - forge install foundry-rs/forge-std@v1.5.2
  build:
    commands:
      - pwd
      - forge build
      - ls
      - ls out
      - zip -r /tmp/contract.zip ./out
      - forge test
      - mkdir coverage
      - forge coverage --report lcov
      - genhtml lcov.info --branch-coverage --output-dir coverage
      - zip -r /tmp/coverage.zip ./coverage
artifacts:
  secondary-artifacts:
    genAICOV:
      base-directory: /tmp
      files:
        - coverage.zip
      name: coverage.zip
    genAIABI:
      base-directory: out/GenAINFT.sol
      files:
        - GenerativeAINFT.json
      name: GenerativeAINFT.json
  discard-paths: yes
